Category.create!([
  {
    name: "Recurring",
    description: "Regularly recurring tasks generated by Recurring Task Templates. These task occur in daily, weekly, monthly, or yearly rhythms (tasks like devotionals, budgeting, haircuts, etc.)",
    color: "#330066",
    icon: "repeat"
  }
])
