task_terminator:
  cron: '1 0 * * *'
  class: TaskTerminationJob
  queue: default
  description: "Check if any tasks have failed on time, and handle updates accordingly"
wave_terminator:
  cron: '11 0 * * *'
  class: WaveTerminationJob
  queue: default
  description: "Check if current wave has ended, then handle updates and rollover if it has"
